"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# Standard Python Libraries
import os
from pathlib import Path
from datetime import timedelta

# Third-party libraries
import dj_database_url
from decouple import config
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv(Path(__file__).resolve().parent.parent / '.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '16.52.17.116', '52.44.192.66','admin.softex-labs.xyz','appcitas.softex-labs.xyz']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'usuarios',
    'rest_framework',
    'citas',

    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',  # SEGURIDAD: JWT blacklist para logout
    'organizacion',
    'marketing',
    'guide',
    'axes',
    'csp',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'organizacion.middleware.OrganizacionMiddleware',  # Multi-tenancy: identifica el tenant
    'core.tenant_middleware.TenantSchemaMiddleware',  # DATABASE-PER-TENANT: setea search_path de PostgreSQL
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# The 'default' database is configured using the DATABASE_URL environment
# variable. This is the standard for platforms like Render.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
        # Persistent connections for better performance with sync workers
        # Aumentado de 60s a 600s (10 minutos) para reducir overhead de reconexiones
        'CONN_MAX_AGE': 600,
        # Health checks para validar que las conexiones estén activas
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            'connect_timeout': 10,
            # DATABASE-PER-TENANT: Configurar search_path por defecto
            'options': '-c search_path=public',
        }
    }
}

# DATABASE-PER-TENANT: Router para dirigir queries al schema correcto
DATABASE_ROUTERS = ['core.tenant_router.TenantRouter']


# Caching configuration for Redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # Using DB 1 for caching
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Pool de conexiones para mejor manejo de concurrencia
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,  # Máximo 50 conexiones simultáneas
                "retry_on_timeout": True,  # Reintentar si hay timeout
            },
            # Timeouts para evitar bloqueos
            "SOCKET_CONNECT_TIMEOUT": 5,  # 5 segundos para conectar
            "SOCKET_TIMEOUT": 5,  # 5 segundos para operaciones
        }
    }
}

# Session configuration - usar Redis en lugar de base de datos
# Mejora la concurrencia y reduce queries a PostgreSQL
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,  # SECURITY: Minimum 8 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'usuarios.validators.ComplexityPasswordValidator',  # SECURITY: Custom validator for complexity
    },
]

AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesBackend',
    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es' # Changed to Spanish as default

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True # Added for localized formatting of data

# Custom format for Colombian Peso (COP)
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','

USE_TZ = True


# Celery Configuration
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2'  # Using DB 2 for Celery
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/2'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Define the languages that your site supports
LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

# Define where Django should look for translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/django-static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Frontend URL for magic links in emails
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://www.softex-labs.xyz')

CORS_ALLOWED_ORIGINS = [
    'http://16.52.17.116',
    'https://16.52.17.116',
    'http://52.44.192.66',
    'https://52.44.192.66',
    'http://appcitas.softex-labs.xyz',
    'https://appcitas.softex-labs.xyz',  # Backend API (HTTPS)
    'https://admin.softex-labs.xyz',  # Django Admin
    'http://admin.softex-labs.xyz',  # Django Admin (HTTP)
    'https://www.softex-labs.xyz',  # Frontend principal (React)
    'https://softex-labs.xyz',  # Sin www
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3002',
    'http://127.0.0.1:3002',
]

# CORS: Allow all headers needed for JWT authentication
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-organization-id',  # Multi-tenant header
]

CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Anonymous users: 100 requests per hour
        'user': '1000/hour',  # Authenticated users: 1000 requests per hour
        'staff': '5000/hour',  # Staff users: 5000 requests per hour
        # SECURITY: Throttles específicos para endpoints públicos
        'public_booking_ip': '5/hour',  # Máximo 5 citas por hora por IP
        'public_booking_email': '3/day',  # Máximo 3 citas por día por email
        'magic_link': '3/hour',  # Máximo 3 magic links por hora por email
    },
    # SECURITY: Custom exception handler to prevent information disclosure
    'EXCEPTION_HANDLER': 'core.exception_handlers.custom_exception_handler',
}

# JWT Configuration - Sincronizado con el idle timer del frontend (15 minutos)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Tiempo de vida del token de acceso
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Tiempo de vida del refresh token
    'ROTATE_REFRESH_TOKENS': True,                   # Rotar refresh token al usarlo
    'BLACKLIST_AFTER_ROTATION': False,               # No usar blacklist (requiere app adicional)
    'UPDATE_LAST_LOGIN': True,                       # Actualizar último login

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Axes configuration
AXES_FAILURE_LIMIT = 5  # Lock out after 5 failed attempts
AXES_COOLOFF_TIME = 1   # Wait 1 hour before allowing attempts again

# CSP Configuration - Permitir HTTP y HTTPS
CSP_DEFAULT_SRC = ('self',)
CSP_SCRIPT_SRC = (
    'self',
    'http://localhost:3000', 'http://127.0.0.1:3000',
    'http://localhost:3002', 'http://127.0.0.1:3002',
    'http://appcitas.softex-labs.xyz', 'https://appcitas.softex-labs.xyz',
    'http://16.52.17.116', 'https://16.52.17.116',
    'http://admin.softex-labs.xyz', 'https://admin.softex-labs.xyz',
    'https://www.softex-labs.xyz', 'https://softex-labs.xyz'
)
CSP_STYLE_SRC = (
    'self', 'unsafe-inline',
    'http://localhost:3000', 'http://127.0.0.1:3000',
    'http://localhost:3002', 'http://127.0.0.1:3002',
    'http://appcitas.softex-labs.xyz', 'https://appcitas.softex-labs.xyz',
    'http://16.52.17.116', 'https://16.52.17.116',
    'http://admin.softex-labs.xyz', 'https://admin.softex-labs.xyz',
    'https://www.softex-labs.xyz', 'https://softex-labs.xyz'
)
CSP_IMG_SRC = (
    'self', 'data:',
    'http://localhost:3000', 'http://127.0.0.1:3000',
    'http://localhost:3002', 'http://127.0.0.1:3002',
    'http://appcitas.softex-labs.xyz', 'https://appcitas.softex-labs.xyz',
    'http://16.52.17.116', 'https://16.52.17.116',
    'http://admin.softex-labs.xyz', 'https://admin.softex-labs.xyz',
    'https://www.softex-labs.xyz', 'https://softex-labs.xyz'
)
CSP_FONT_SRC = ('self',)
CSP_CONNECT_SRC = (
    'self',
    'http://localhost:3000', 'http://127.0.0.1:3000',
    'http://localhost:3002', 'http://127.0.0.1:3002',
    'http://appcitas.softex-labs.xyz', 'https://appcitas.softex-labs.xyz',
    'http://16.52.17.116', 'https://16.52.17.116',
    'http://52.44.192.66', 'https://52.44.192.66',
    'http://admin.softex-labs.xyz', 'https://admin.softex-labs.xyz',
    'https://www.softex-labs.xyz', 'https://softex-labs.xyz'
)
CSP_FRAME_ANCESTORS = ('none',)
CSP_BASE_URI = ('self',)
CSP_FORM_ACTION = (
    'self',
    'http://16.52.17.116', 'https://16.52.17.116',
    'http://appcitas.softex-labs.xyz', 'https://appcitas.softex-labs.xyz',
    'http://admin.softex-labs.xyz', 'https://admin.softex-labs.xyz'
)

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('SMTP_HOST', default='')
EMAIL_PORT = config('SMTP_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('TO_EMAIL', default='')
EMAIL_HOST_PASSWORD = config('SMTP_PASS', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')

# ============================================================================
# TWILIO WHATSAPP CONFIGURATION
# ============================================================================
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_FROM = os.getenv('TWILIO_WHATSAPP_FROM', '')

# ============================================================================
# SECURITY HEADERS - Solo activos en producción (DEBUG=False)
# ============================================================================
if not DEBUG:
    # HTTPS/SSL Configuration
    SECURE_SSL_REDIRECT = True  # Redirige todo el tráfico HTTP a HTTPS
    SESSION_COOKIE_SECURE = True  # Cookies de sesión solo por HTTPS
    CSRF_COOKIE_SECURE = True  # Cookies CSRF solo por HTTPS

    # SECURITY: CSRF Protection enhancements
    CSRF_COOKIE_HTTPONLY = True  # Previene acceso a cookie CSRF desde JavaScript
    CSRF_USE_SESSIONS = False  # Usa cookie en lugar de sesión (más seguro con API)
    CSRF_COOKIE_SAMESITE = 'Strict'  # Previene CSRF cross-site

    # Security Headers
    SECURE_BROWSER_XSS_FILTER = True  # Activa el filtro XSS del navegador
    SECURE_CONTENT_TYPE_NOSNIFF = True  # Previene MIME type sniffing
    X_FRAME_OPTIONS = 'DENY'  # Previene clickjacking (no permite iframes)

    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = 31536000  # 1 año - Fuerza HTTPS por este tiempo
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Aplica HSTS a subdominios
    SECURE_HSTS_PRELOAD = True  # Permite incluir en listas de precarga HSTS

    # Proxy Configuration (para servidores detrás de nginx/apache)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # En desarrollo, permitir HTTP
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
