# Generated by Django 5.0.7 on 2025-09-10 19:33

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name='Recurso')

class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_create_groups'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]