# Generated by Django 5.0.6 on 2025-09-25 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_create_recurso_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sede',
            name='organizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='organizacion.organizacion'),
        ),
    ]
