# Generated by Django 5.0.6 on 2025-09-25 20:52

from django.db import migrations


def forwards_func(apps, schema_editor):
    """
    Crea una organización por defecto y asocia las sedes y usuarios existentes a ella.
    """
    Organizacion = apps.get_model("organizacion", "Organizacion")
    Sede = apps.get_model("organizacion", "Sede")
    PerfilUsuario = apps.get_model("usuarios", "PerfilUsuario")

    # Crea una organización por defecto
    default_organizacion = Organizacion.objects.create(nombre="Organización Principal")

    # Actualiza las sedes existentes
    for sede in Sede.objects.all():
        sede.organizacion = default_organizacion
        sede.save()

    # Actualiza los perfiles de usuario existentes
    for perfil in PerfilUsuario.objects.all():
        perfil.organizacion = default_organizacion
        perfil.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_organizacion_alter_sede_nombre_sede_organizacion'),
        ('usuarios', '0004_perfilusuario_barrio_perfilusuario_ciudad_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
