# Generated by Django 5.0.6 on 2025-10-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0005_organizacion_sede_organizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
