# Generated by Django 5.0.6 on 2025-10-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0006_organizacion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='database_name',
            field=models.CharField(blank=True, help_text='Nombre de base de datos dedicada (solo para enterprise)', max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si está activo el tenant'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='schema_name',
            field=models.CharField(blank=True, db_index=True, help_text='PostgreSQL schema name for this tenant', max_length=63, unique=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='organizacion',
            table='organizacion_organizacion',
        ),
    ]
