# Generated by Django 5.0.7 on 2025-08-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0002_create_groups'),
        ('usuarios', '0002_perfilusuario_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='sedes_administradas',
            field=models.ManyToManyField(blank=True, related_name='administradores', to='organizacion.sede'),
        ),
    ]
