# Generated by Django 5.0.6 on 2025-10-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['email', '-attempted_at'], name='usuarios_fa_email_552998_idx'), models.Index(fields=['ip_address', '-attempted_at'], name='usuarios_fa_ip_addr_31aaa0_idx')],
            },
        ),
    ]
