# Generated by Django 5.0.6 on 2025-10-19 22:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0006_organizacion_slug'),
        ('usuarios', '0008_add_failed_login_attempt_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='additional_roles',
            field=models.JSONField(blank=True, default=list, help_text='Roles adicionales del usuario (ej: ["cliente", "colaborador"])', verbose_name='Roles Adicionales'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el usuario tiene acceso activo a esta organización', verbose_name='Membresía Activa'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Permisos granulares adicionales en formato JSON', verbose_name='Permisos Personalizados'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('sede_admin', 'Administrador de Sede'), ('colaborador', 'Colaborador'), ('cliente', 'Cliente')], db_index=True, default='cliente', help_text='Rol principal del usuario en esta organización', max_length=20, verbose_name='Rol Principal'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='organizacion.organizacion'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='sede',
            field=models.ForeignKey(blank=True, help_text='Sede principal del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_principales', to='organizacion.sede', verbose_name='Sede Principal'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='sedes',
            field=models.ManyToManyField(blank=True, help_text='Sedes donde este usuario trabaja (para colaboradores)', related_name='colaboradores_multisede', to='organizacion.sede', verbose_name='Sedes de Trabajo'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='sedes_administradas',
            field=models.ManyToManyField(blank=True, help_text='Sedes que este usuario administra (para sede_admin)', related_name='administradores', to='organizacion.sede', verbose_name='Sedes Administradas'),
        ),
    ]
