# Generated by Django 5.0.7 on 2025-08-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Asistio', 'Asistio'), ('No Asistio', 'No Asistio')], default='Pendiente', max_length=20),
        ),
    ]
