# Generated by Django 5.0.7 on 2025-08-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='recursos',
            field=models.ManyToManyField(blank=True, related_name='citas', to='citas.recurso'),
        ),
    ]
