# Generated by Django 5.0.7 on 2025-08-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_recurso_cita_recursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='recursos', to='citas.horario'),
        ),
    ]
