# Generated by Django 5.0.7 on 2025-08-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_recurso_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='duracion_estimada',
            field=models.IntegerField(default=30),
        ),
    ]
