# Generated by Django 5.0.7 on 2025-08-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_servicio_duracion_estimada'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
