# Generated by Django 5.0.7 on 2025-08-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_recurso_metadata_servicio_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Asistio', 'Asistió'), ('No Asistio', 'No Asistió')], default='Pendiente', max_length=20),
        ),
    ]
