# Generated by Django 5.0.7 on 2025-08-23 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_alter_cita_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='horarios',
        ),
        migrations.AddField(
            model_name='horario',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='citas.recurso'),
        ),
    ]
