# Generated by Django 5.0.7 on 2025-08-23 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_alter_horario_recurso'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='organizacion.sede'),
        ),
        migrations.AddField(
            model_name='horario',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='organizacion.sede'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='organizacion.sede'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='organizacion.sede'),
        ),
    ]
