# Generated by Django 5.0.7 on 2025-09-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0013_auto_20250823_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Asistio', 'Asistió'), ('No Asistio', 'No Asistió')], db_index=True, default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
