# Generated by Django 5.0.7 on 2025-09-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0014_alter_cita_estado_alter_cita_fecha_alter_cita_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio del servicio', max_digits=10),
        ),
    ]