# Generated by Django 5.0.7 on 2025-09-05 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0015_servicio_precio'),
        ('organizacion', '0002_create_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='Ej: Almuerzo, Reunión, Cita personal', max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='citas.recurso')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='organizacion.sede')),
            ],
        ),
    ]
