# Generated by Django 5.0.7 on 2025-09-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0016_bloqueo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='sede',
        ),
    ]
