# Generated by Django 5.0.7 on 2025-09-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0018_recurso_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloqueo',
            name='sede',
        ),
    ]
