# Generated by Django 5.0.7 on 2025-09-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0019_remove_bloqueo_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
