# Generated by Django 5.0.7 on 2025-09-10 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0020_recurso_email'),
        ('organizacion', '0003_create_recurso_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='recurso',
        ),
        migrations.RemoveField(
            model_name='bloqueo',
            name='recurso',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='recursos',
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='organizacion.sede')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bloqueo',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='citas.colaborador'),
        ),
        migrations.AddField(
            model_name='cita',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='citas', to='citas.colaborador'),
        ),
        migrations.AddField(
            model_name='horario',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='citas.colaborador'),
        ),
        migrations.DeleteModel(
            name='Recurso',
        ),
    ]
