# Generated by Django 5.0.7 on 2025-09-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0021_remove_horario_recurso_remove_bloqueo_recurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
