# Generated by Django 5.0.7 on 2025-09-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0022_cita_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(related_name='citas', to='citas.servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
