# Generated by Django 5.0.7 on 2025-09-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0023_remove_cita_servicio_cita_servicios_alter_cita_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='colaboradores', to='citas.servicio'),
        ),
    ]
