# Generated by Django 5.0.6 on 2025-09-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0024_colaborador_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloqueo',
            name='fecha_fin',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bloqueo',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], db_index=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
