# Generated by Django 5.0.6 on 2025-09-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0025_alter_bloqueo_fecha_fin_alter_bloqueo_fecha_inicio_and_more'),
        ('organizacion', '0005_auto_20250925_1552'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colaborador',
            unique_together={('sede', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('sede', 'nombre')},
        ),
    ]
