# Generated by Django 5.0.6 on 2025-10-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0027_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bloqueo',
            name='bloqueo_fechas_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='cita_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='cita_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='cita_fecha_estado_idx',
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='cita_sede_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='colaborador',
            name='colaborador_sede_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horario_dia_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicio',
            name='servicio_sede_idx',
        ),
        migrations.AddField(
            model_name='cita',
            name='email_cliente',
            field=models.EmailField(blank=True, db_index=True, help_text='Email del cliente para reservas como invitado', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='telefono_cliente',
            field=models.CharField(blank=True, help_text='Teléfono del cliente para reservas como invitado', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0.0, help_text='Precio del servicio', max_digits=10),
        ),
    ]
